spring:
  application:
    name: ms-stock
server:
  port: 8080

resilience4j:
  retry:
    instances:
      stock-price:
        wait-duration: 2s
        max-attempts: 2

#eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka